import Head from "next/head";
import Image from "next/image";
import { AiFillLinkedin, AiFillGithub, SiIndeed } from "react-icons/ai";
import useState from "react";
export default function Home() {
  function goToWeb(link) {
    window.open(link);
  }
  // const [darkMode, setDarkMode] = useState(false);
  const Linkedin = "https://www.linkedin.com/in/anthony-silva-3424a4253/";
  const GitHub = "https://github.com/anthonysilva98";
  const Resume = "Anthony_Silva_Website_Resume.pdf";
  return (
    <div>
      <Head>
        <title>Anthony Silva Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <ul className="flex items-center">
              <li></li>
              <li>
                <a
                  className="bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                  onClick={() => {
                    window.open(Resume);
                  }}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 font-medium text-teal-600 md:text-6xl">
              Anthony Silva
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl"> Software developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Full stack software developer that specializes in mobile
              development using JavaScript and react native.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <button onClick={() => goToWeb(Linkedin)}>
              <AiFillLinkedin />
            </button>
            <button onClick={() => goToWeb(GitHub)}>
              <AiFillGithub />
            </button>
          </div>
        </section>
        <section>
          <h3 className="text-3xl py-10 justify-center flex  text-gray-600">
            Tech Stack
          </h3>
          <section>
            <div className="grid grid-cols-3 pt-10">
              <div className="flex justify-center align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-30 pl-12"
                    src="/ReactNativelogo.jfif"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  React Native
                </p>
              </div>
              <div className="flex justify-center self-auto py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="/JSLogo.png"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  JavaScript
                </p>
              </div>
              <div className="flex justify-center align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="/ExpoLogo.png"
                  />
                </picture>
                <li className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  Expo
                </li>
              </div>
              <div className="flex justify-center align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="/FirebaseLogo.jfif"
                  />
                </picture>
                <p className="list-none text-2xl  align-middle pl-5 justify-center py-5  text-gray-600">
                  Firebase
                </p>
              </div>
              <div className="flex justify-center align-middle py-5">
                <picture>
                  <img
                    alt="vercel.svg"
                    className="h-20 w-20"
                    src="/TSLogo.png"
                  />
                </picture>
                <p className="list-none text-2xl align-middle pl-5 justify-center py-5  text-gray-600">
                  TypeScript
                </p>
              </div>
            </div>
            <div>
              <h3 className="text-3xl pt-20 justify-center flex text-gray-600">
                React-Native Projects Portfolio
              </h3>
            </div>
          </section>
          <div className="lg:flex gap-10 justify-center grid ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center">
              <p className="text-2xl py-1 text-gray-800 flex-1">
                UPS Tracker Demo
              </p>
              <video autoPlay loop muted className="h-300">
                <source src="/upsDemo.mp4" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-gray-800">graphQL</p>
              <p className="text-md py-1 text-gray-800">
                Custom Graph QL backend that allows filtering, searching and
                viewing of items that in a Firebase database.
              </p>
              <p className="text-2xl py-1 text-black-800">TailwindCSS</p>
              <p className="text-md py-1 text-gray-800">
                Built out all custom components using TailwindCSS that allows
                for easy creation and styling.
              </p>
              <p className="text-2xl py-1 text-gray-800">FireBase</p>
              <p className="text-md py-1 text-gray-800">
                Using Firebase database, was able to store the data in JSON
                format to allow for easy requests and data manipulation.
              </p>
            </div>
            <div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <p className="text-2xl py-1 text-gray-800 flex-1">
                  UberEats App Demo
                </p>
                <video autoPlay loop muted className="h-300">
                  <source src="/UberEats.mp4" type="video/mp4" />
                </video>
                <p className="text-2xl py-1 text-gray-800">Google Places Api</p>
                <p className="text-md py-1 text-gray-800">
                  Built out custom components that allow for a user to select
                  where they would like to go and render components on screen
                  based off of this decision.
                </p>
                <p className="text-2xl py-1 text-gray-800">FireBase</p>
                <p className="text-md py-1 text-gray-800">
                  Using Firebase Firstore, was able to store and show users
                  their orders that were created with the user interface.
                  {/* Using Firebase Firestore, was able to allow users to create an
                  order which would be sent to Firestore to be retreived when
                  showing their final order. Firebase backend that handles
                  orders that are sent out through the app */}
                </p>
                <p className="text-2xl py-1 text-gray-800">Yelp Api</p>
                <p className="text-md py-1 text-gray-800">
                  With integration of the Yelp API, I was able to display
                  information about the resturants queried from the google
                  places API.
                </p>
                <p className="text-2xl py-1 text-gray-800">Redux</p>
                <p className="text-md py-1 text-gray-800">
                  Redux is used in this project for state management and allows
                  users to create order and push it to firebase backend
                </p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-2xl py-1 text-gray-800">Step Counter App</p>
              <video autoPlay loop muted className="h-300">
                <source src="/StepCounterApp.mov" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-gray-800 flex-1">
                Apple HealthKit
              </p>
              <p className="text-md py-1 text-gray-800">
                Integrating with Apple HealthKit, I was able to get information
                provided by Apple devices that shows health information.
              </p>
              <p></p>
              <p className="text-2xl py-1 text-gray-800">
                React Native Reanimated
              </p>
              <p className="text-md py-1 text-gray-800">
                Using React Native Reanimated, I was able to create custom
                components that drive the animations that are used to show users
                goal completion
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10 justify-center grid">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 justify-center">
              <p className="text-2xl py-1 text-gray-800">Uber Rideshare Demo</p>
              <video autoPlay loop muted className="h-300">
                <source src="/UberDemo.mov" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-gray-800">Google Places API</p>
              <p className="text-md py-1 text-gray-800">
                Google Places API used for getting places and autofilling for
                better user experience
              </p>
              <p className="text-2xl py-1 text-black-800">TailwindCSS</p>
              <p className="text-md py-1 text-gray-800">
                Allows for easy and fast paced components to be built
              </p>
              <p className="text-2xl py-1 text-gray-800">
                Google Distance Matrix
              </p>
              <p className="text-md py-1 text-gray-800">
                Google Distance matrix allows for calculating how long a ride
                will take along with how much that ride should cost
              </p>
              <p className="text-2xl py-1 text-gray-800">Redux</p>
              <p className="text-md py-1 text-gray-800">
                Used for state management and allows for users to request rides
                and set destinations start points
              </p>
            </div>
            <div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <p className="text-2xl py-1 text-gray-800">Nike App Demo</p>
                <video autoPlay loop muted className="h-300">
                  <source src="/NikeAPP.mov" type="video/mp4" />
                </video>
                <p className="text-2xl py-1 text-gray-800">Redux</p>
                <p className="text-md py-1 text-gray-800">
                  Used for state management accross the app and allows user to
                  build cart before placeing their order
                </p>
                <p className="text-2xl py-1 text-gray-800">
                  Custom Restful Api
                </p>
                <p className="text-md py-1 text-gray-800">
                  Custom Restful API that uses Node.js and Express to make
                  requests to our backend.
                </p>
                <p className="text-2xl py-1 text-gray-800">MongoDB</p>
                <p className="text-md py-1 text-gray-800">
                  MongoDB database was used in this project as our database and
                  allows users orders to be saved and retreived.
                </p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-2xl py-1 text-gray-800">Twitter Clone</p>
              <video autoPlay loop muted className="h-300">
                <source src="/TwitterClone.mp4" type="video/mp4" />
              </video>
              <p className="text-2xl py-1 text-gray-800">Express</p>
              <p className="text-md py-1 text-gray-800">
                Express was used in this project to allow for custom APIs to our
                backend.
              </p>
              <p className="text-2xl py-1 text-gray-800">Prisma</p>
              <p className="text-md py-1 text-gray-800">
                Prisma was used in this project as our database used for storing
                users, tweets, and other information related to tweets.
              </p>
              <p className="text-2xl py-1 text-gray-800">Node</p>
              <p className="text-md py-1 text-gray-800">
                Used for state management accross the app and allows user to
                build cart before placeing their order.
              </p>
              <p className="text-2xl py-1 text-gray-800">AWS SMS</p>
              <p className="text-md py-1 text-gray-800">
                Used for state management accross the app and allows user to
                build cart before placeing their order.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
